package com.netsymptom.stepdefs;

import com.netsymptom.pages.HomePage;
import com.netsymptom.utils.DriverManager;
import io.cucumber.java.en.*;
import org.openqa.selenium.WebDriver;
import org.testng.Assert;

public class NavigationSteps {

    private final HomePage page;
    private final WebDriver driver;

    public NavigationSteps() {
        this.driver = DriverManager.getDriver();
        this.page   = new HomePage(driver);
    }

    @Given("I navigate to the deep link {string}")
    public void iNavigateToTheDeepLink(String slug) {
        page.openDeepLink(slug);
    }

    @Then("the URL hash should contain {string}")
    public void theUrlHashShouldContain(String fragment) {
        String url = driver.getCurrentUrl();
        Assert.assertTrue(url.contains(fragment),
            "URL '" + url + "' does not contain '" + fragment + "'");
    }

    @Then("the meta description should contain {string}")
    public void theMetaDescriptionShouldContain(String text) {
        String desc = page.getMetaDescription();
        Assert.assertTrue(desc != null && desc.contains(text),
            "Meta description '" + desc + "' does not contain '" + text + "'");
    }

    @Then("the page title should be updated for the {string} slug")
    public void thePageTitleShouldBeUpdatedForTheSlug(String slug) {
        String title = page.getPageTitle();
        Assert.assertFalse(title == null || title.trim().isEmpty(),
            "Page title is empty for slug: " + slug);
    }

    @Then("the results should be auto-generated")
    public void theResultsShouldBeAutoGenerated() {
        page.results.waitForResults();
        Assert.assertTrue(page.results.isVisible(),
            "Results were not auto-generated for the deep link");
    }

    @When("I click the footer Privacy Policy link")
    public void iClickTheFooterPrivacyPolicyLink() {
        page.footer.clickPrivacyPolicyLink();
    }

    @When("I click the footer Terms of Service link")
    public void iClickTheFooterTermsOfServiceLink() {
        page.footer.clickTermsOfServiceLink();
    }

    @Then("the footer should contain copyright text")
    public void theFooterShouldContainCopyrightText() {
        String text = page.footer.getCopyrightText();
        Assert.assertTrue(text.contains("NetSymptom") || text.contains("©"),
            "Footer copyright text is missing or incorrect: " + text);
    }

    @Then("the knowledge base section should be visible")
    public void theKnowledgeBaseSectionShouldBeVisible() {
        Assert.assertTrue(page.knowledgeBase.isVisible(),
            "Knowledge base section is not visible");
    }

    @Then("the knowledge base should contain {int} articles")
    public void theKnowledgeBaseShouldContainArticles(int expected) {
        int actual = page.knowledgeBase.getArticleCount();
        Assert.assertEquals(actual, expected,
            "Expected " + expected + " articles in knowledge base but found " + actual);
    }

    @Then("the about section should be visible")
    public void theAboutSectionShouldBeVisible() {
        Assert.assertTrue(page.about.isVisible(), "About section is not visible");
    }

    @Then("the hero section headline should be visible")
    public void theHeroSectionHeadlineShouldBeVisible() {
        Assert.assertTrue(page.hero.isHeadlineVisible(), "Hero headline is not visible");
    }
}
